### ISSUE TITLE
Unknow Error

### ISSUE THREAD

**Issue by ajcorrea** [rokam/hass-sunweg#45]
Trying to add the integration to Home Assistant 2023.12.3 and getting Unknow Error, the log says that user or passowrd wrong, but it´s ok.

Logs:

`Dec 20 16:05:59 homeassistant homeassistant[688]: #033[31m2023-12-20 16:05:59.833 ERROR (MainThread) [aiohttp.server] Error handling request
Dec 20 16:05:59 homeassistant homeassistant[688]: Traceback (most recent call last):
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
Dec 20 16:05:59 homeassistant homeassistant[688]:     resp = await request_handler(request)
Dec 20 16:05:59 homeassistant homeassistant[688]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
Dec 20 16:05:59 homeassistant homeassistant[688]:     resp = await handler(request)
Dec 20 16:05:59 homeassistant homeassistant[688]:            ^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
Dec 20 16:05:59 homeassistant homeassistant[688]:     return await handler(request)
Dec 20 16:05:59 homeassistant homeassistant[688]:            ^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
Dec 20 16:05:59 homeassistant homeassistant[688]:     return await handler(request)
Dec 20 16:05:59 homeassistant homeassistant[688]:            ^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
Dec 20 16:05:59 homeassistant homeassistant[688]:     return await handler(request)
Dec 20 16:05:59 homeassistant homeassistant[688]:            ^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
Dec 20 16:05:59 homeassistant homeassistant[688]:     return await handler(request)
Dec 20 16:05:59 homeassistant homeassistant[688]:            ^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
Dec 20 16:05:59 homeassistant homeassistant[688]:     return await handler(request)
Dec 20 16:05:59 homeassistant homeassistant[688]:            ^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 233, in auth_middleware
Dec 20 16:05:59 homeassistant homeassistant[688]:     return await handler(request)
Dec 20 16:05:59 homeassistant homeassistant[688]:            ^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
Dec 20 16:05:59 homeassistant homeassistant[688]:     response = await handler(request)
Dec 20 16:05:59 homeassistant homeassistant[688]:                ^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
Dec 20 16:05:59 homeassistant homeassistant[688]:     result = await handler(request, **request.match_info)
Dec 20 16:05:59 homeassistant homeassistant[688]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
Dec 20 16:05:59 homeassistant homeassistant[688]:     return await func(self, request, *args, **kwargs)
Dec 20 16:05:59 homeassistant homeassistant[688]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
Dec 20 16:05:59 homeassistant homeassistant[688]:     return await super().post(request, flow_id)
Dec 20 16:05:59 homeassistant homeassistant[688]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
Dec 20 16:05:59 homeassistant homeassistant[688]:     result = await method(view, request, data, *args, **kwargs)
Dec 20 16:05:59 homeassistant homeassistant[688]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
Dec 20 16:05:59 homeassistant homeassistant[688]:     result = await self._flow_mgr.async_configure(flow_id, data)
Dec 20 16:05:59 homeassistant homeassistant[688]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 293, in async_configure
Dec 20 16:05:59 homeassistant homeassistant[688]:     result = await self._async_handle_step(
Dec 20 16:05:59 homeassistant homeassistant[688]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 389, in _async_handle_step
Dec 20 16:05:59 homeassistant homeassistant[688]:     result: FlowResult = await getattr(flow, method)(user_input)
Dec 20 16:05:59 homeassistant homeassistant[688]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/config/custom_components/sunweg/config_flow.py", line 44, in async_step_user
Dec 20 16:05:59 homeassistant homeassistant[688]:     login_response = await self.hass.async_add_executor_job(self.api.authenticate)
Dec 20 16:05:59 homeassistant homeassistant[688]:                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
Dec 20 16:05:59 homeassistant homeassistant[688]:     result = self.fn(*self.args, **self.kwargs)
Dec 20 16:05:59 homeassistant homeassistant[688]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/local/lib/python3.11/site-packages/sunweg/api.py", line 63, in authenticate
Dec 20 16:05:59 homeassistant homeassistant[688]:     result = self._post(SUNWEG_LOGIN_PATH, user_data)
Dec 20 16:05:59 homeassistant homeassistant[688]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/local/lib/python3.11/site-packages/sunweg/api.py", line 268, in _post
Dec 20 16:05:59 homeassistant homeassistant[688]:     result = self._treat_response(res)
Dec 20 16:05:59 homeassistant homeassistant[688]:              ^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 20 16:05:59 homeassistant homeassistant[688]:   File "/usr/local/lib/python3.11/site-packages/sunweg/api.py", line 279, in _treat_response
Dec 20 16:05:59 homeassistant homeassistant[688]:     raise SunWegApiError(result["message"])
Dec 20 16:05:59 homeassistant homeassistant[688]: sunweg.api.SunWegApiError: Usuário ou senha inválidos!#033[0m`

**Comment by rokam** [comment]
By the log, that is what sunweg api is returning. As the integration will be available directly on homeassistant 2024.01 version, I won't provide any additional support here.
